# Generated by Django 5.0.3 on 2025-09-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver_email',
            field=models.EmailField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
