# Generated by Django 5.2.6 on 2025-09-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_order_receiver_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed_attempt', 'Failed Attempt'), ('returned', 'Returned')], default='pending', max_length=50),
        ),
    ]
